<a href="https://colab.research.google.com/github/Super-rookie-Py/_MachineLearning_Class/blob/main/%EB%B0%95%EA%B1%B4%EC%9A%B0_%EB%82%98%EC%9D%B4%EB%B8%8C%EB%B2%A0%EC%9D%B4%EC%A6%88%EB%B6%84%EB%A5%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

keonwoo Park 2020/10/14

In [58]:
import numpy as np
import pandas as pd

from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.datasets import load_breast_cancer, load_wine
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn import metrics
import multiprocessing

## 유방암 데이터 나이브베이즈 분류

In [7]:
cancer = load_breast_cancer()
cancer_df = pd.DataFrame(data=cancer.data, columns=cancer.feature_names)
cancer_df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [9]:
scaler = StandardScaler()
cancer_scaled = scaler.fit_transform(cancer_df)
cancer_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [10]:
X_train , X_test, y_train, y_test = train_test_split(cancer_scaled, cancer.target, test_size=0.2)

In [11]:
model = BernoulliNB()
model.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [12]:
predict = model.predict(X_train)
acc =metrics.accuracy_score(y_train, predict)
f1 = metrics.f1_score(y_train, predict, average=None)

print("Train Accuracy: {}".format(acc))
print("Train F1 score: {}".format(f1))

Train Accuracy: 0.9340659340659341
Train F1 score: [0.91573034 0.94584838]


In [13]:
predict = model.predict(X_test)
acc =metrics.accuracy_score(y_test, predict)
f1 = metrics.f1_score(y_test, predict, average=None)

print("Test Accuracy: {}".format(acc))
print("Test F1 score: {}".format(f1))

Test Accuracy: 0.956140350877193
Test F1 score: [0.93506494 0.96688742]


## 와인데이터 나이브베이즈 분류기

In [50]:
wine = load_wine()
wine_df = pd.DataFrame(data=wine.data, columns=wine.feature_names)
wine_df.head()

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [51]:
scaler = StandardScaler()
wine_scaled = scaler.fit_transform(wine_df)
wine_scaled

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [52]:
X_train , X_test, y_train, y_test = train_test_split(wine_scaled, wine.target, test_size=0.2)

### 최적의 alpha값 탐색

In [56]:
param_grid = [{
    "alpha": [0.2, 0.4, 0.6, 0.8, 1.0]
}]

In [59]:
gs = GridSearchCV(
    estimator = BernoulliNB(),
    param_grid = param_grid,
    n_jobs = multiprocessing.cpu_count(),
    verbose=True
)

In [60]:
gs.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  25 out of  25 | elapsed:    1.1s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None,
                                   fit_prior=True),
             iid='deprecated', n_jobs=2,
             param_grid=[{'alpha': [0.2, 0.4, 0.6, 0.8, 1.0]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=True)

In [61]:
gs.best_estimator_

BernoulliNB(alpha=0.2, binarize=0.0, class_prior=None, fit_prior=True)

In [62]:
model = gs.best_estimator_
model.fit(X_train, y_train)

BernoulliNB(alpha=0.2, binarize=0.0, class_prior=None, fit_prior=True)

In [63]:
predict = model.predict(X_train)
acc =metrics.accuracy_score(y_train, predict)
f1 = metrics.f1_score(y_train, predict, average=None)

print("Train Accuracy: {}".format(acc))
print("Train F1 score: {}".format(f1))

Train Accuracy: 0.9366197183098591
Train F1 score: [0.94623656 0.91891892 0.95      ]


In [64]:
predict = model.predict(X_test)
acc =metrics.accuracy_score(y_test, predict)
f1 = metrics.f1_score(y_test, predict, average=None)

print("Test Accuracy: {}".format(acc))
print("Test F1 score: {}".format(f1))

Test Accuracy: 0.9444444444444444
Test F1 score: [1.         0.92307692 0.9       ]


## 붓꽃데이터 나이브베이즈 분류기

In [43]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [44]:
# 음수 값을 없애기 위해 MinMaxScaler사용
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)
iris_scaled[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [45]:
X_train , X_test, y_train, y_test = train_test_split(iris_scaled, iris.target, test_size=0.2)

In [46]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
predict = model.predict(X_train)
acc =metrics.accuracy_score(y_train, predict)
f1 = metrics.f1_score(y_train, predict, average=None)

print("Train Accuracy: {}".format(acc))
print("Train F1 score: {}".format(f1))

Train Accuracy: 0.6833333333333333
Train F1 score: [1.         0.68333333 0.        ]


In [48]:
predict = model.predict(X_test)
acc =metrics.accuracy_score(y_test, predict)
f1 = metrics.f1_score(y_test, predict, average=None)

print("Test Accuracy: {}".format(acc))
print("Test F1 score: {}".format(f1))

Test Accuracy: 0.5666666666666667
Test F1 score: [0.94117647 0.58064516 0.        ]
